export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const RESET_ERRORS = 'RESET_ERRORS';
